name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install LFTP
      run: sudo apt-get install -y lftp

    - name: Deploy using FTP
      run: |
        lftp -c "
        open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }};
        lcd .;
        mirror --reverse --delete --verbose . /path-to-your-site;
        rm -rf /public_html;
        mv /path-to-your-site /public_html;
        bye"
