name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy with LFTP
      run: |
        sudo apt-get install -y lftp
        lftp -e "
        set ssl:verify-certificate no;
        open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ftp.faculty.schoolmanagementsystem2.com;
        lcd .;
        mirror --reverse --delete --verbose . /public_html;
        bye
        "
